apiVersion: v1
kind: Service
metadata:
    name: nodeapp
spec:
    type: ClusterIP
    selector:
        app: nodeapp
    ports:
        - port: 3003
          protocol: TCP
          targetPort: 3000
