apiVersion: v1
kind: Service
metadata:
    name: nodeapp
spec:
    type: NodePort
    selector:
        app: nodeapp
    ports:
        - name: http
          nodePort: 30080
          protocol: TCP
          port: 1234
          targetPort: 3000
